#------------------------------------------------------------------------
# Example macro. Process one of
#------------------------------------------------------------------------

# Include default setup
# Use jleic.mac for headless mode or jleicvis.mac for GUI visualization
/control/execute jleic.mac

# BEAGLE generator
/generator/select beagle
/generator/beagle/open beagle_test_data.txt
/generator/beagle/verbose 2

/run/beamOn 1
exit
