  #------------------------------------------------------------------------
  # Macro file for the initialization phase
  #------------------------------------------------------------------------
  #
/control/verbose 0
/run/verbose 0
/geometry/navigator/verbose 0
/tracking/verbose 0

/XTRdetector/setup  jleic2019
/emphyslist/setXTRModel  transpM
/emphyslist/setGammaCut     0.11
/emphyslist/setElectronCut  0.12
/emphyslist/setPositronCut  0.13
/emphyslist/setRadiatorCuts 0.14
/emphyslist/setGammaCut     0.020
/emphyslist/setElectronCut  0.020
/emphyslist/setPositronCut  0.020
/emphyslist/setDetectorCuts 0.020
/run/initialize


# BEAGLE generator
/generator/select beagle
/generator/beagle/open beagle_test_data.txt
/generator/beagle/verbose 2

/run/beamOn 1
exit
