#------------------------------------------------------------------------
# Example macro. Process one of
#------------------------------------------------------------------------

# Include default setup
# Use jleic.mac for headless mode or jleicvis.mac for GUI visualization
/control/execute jleic.mac

# BEAGLE generator
/generator/select beagle
/generator/beagle/open /home/romanov/eic/g4e/g4e-dev/test/beagle/beagle_test_data.txt
/generator/beagle/verbose 0

/run/initialize

/run/beamOn 2
exit
