#  histo1   number of steps/event
/plots/setnbinStep  100
/plots/setSteplow   0.
/plots/setStephigh  10.

#  histo2    Energy Loss (keV)
/plots/setnbinEn 100
/plots/setEnlow 0.0 MeV
/plots/setEnhigh 0.05  MeV
  #
  #  histo3   angle distribution at exit(deg)
/plots/setnbinTh  100
/plots/setThlow    89.  deg
/plots/setThhigh   90. deg
  #
  #  histo4    lateral distribution at exit(mm)
/plots/setnbinR  100
/plots/setRlow   0.  mm
/plots/setRhigh  400. mm
  #
  #  histo5   kinetic energy of the primary at exit(MeV)
/plots/setnbinTt  100
/plots/setTtlow   0.   MeV
/plots/setTthigh  10000. MeV
  #
  #  histo6    angle distribution of backscattered primaries(deg)
/plots/setnbinThback  100
/plots/setThlowback   0.   deg
/plots/setThhighback  40. deg
  #
  #  histo7    kinetic energy of the backscattered primaries (MeV)
/plots/setnbinTb  100
/plots/setTblow   0.   MeV
/plots/setTbhigh  10000.  MeV
  #
  #
  #  histo8    kinetic energy of the charged secondaries (MeV)
/plots/setnbinTsec  100
/plots/setTseclow   0.   MeV
/plots/setTsechigh  100.  MeV
  #
  #  histo9      z of secondary charged vertices(mm)
/plots/setnbinzvertex  100
/plots/setzlow   0.   mm
/plots/setzhigh  100. mm
  #
  #  histo10      kinetic energy of gammas escaping the absorber (keV)
/plots/setnbinGamma   500
  # chto by imetx 50. nado pisatx MeV, hotq budut keV
/plots/setElowGamma   0.   MeV
/plots/setEhighGamma  50.  MeV
  #
  #------------------------------------------------------------------------
  # Macro file for the initialization phase
  #------------------------------------------------------------------------
  #
/control/verbose 2
/run/verbose 2
/geometry/navigator/verbose 0
  #
  # CERN test beam setup DEPFET/TRD
  #
/XTRdetector/setup  jleic2019
  #/XTRdetector/setup  vertex16
  #/XTRdetector/setup depfet09
  #/XTRdetector/setup fdc15
  #
  # these commands do not change energy cuts???
  #
  # Set XTR model (default: transpM). Name list consits:
  # gammaR, gammaM, regR, regM, strawR, transpR, transpM
  #
  # R - XTR dE/dx models, M - XTR flux after radiator models
  #
/emphyslist/setXTRModel  transpM
  #/emphyslist/setXTRModel  transpR
  #/emphyslist/setXTRModel  gammaM
  #/emphyslist/setXTRModel  gammaR
  #/emphyslist/setXTRModel  strawR
  #/emphyslist/setXTRModel  regM
  #/emphyslist/setXTRModel  regR
  #
  #/emphyslist/eMinEnergy 100.
  #/emphyslist/gMinEnergy 100.
  #
  #
  #/run/particle/applyCuts
  #
  # set cuts in XTR radiator
  #
/emphyslist/setGammaCut     0.11
/emphyslist/setElectronCut  0.12
/emphyslist/setPositronCut  0.13
/emphyslist/setRadiatorCuts 0.14
  #
  # set cuts in XTR detector
  #
/emphyslist/setGammaCut    0.020
/emphyslist/setElectronCut 0.020
/emphyslist/setPositronCut 0.020
  #
/emphyslist/setDetectorCuts 0.020
  #
  #
/run/initialize
  #
  #--------------------------------------------------------------------

  #--------------------------------------------------------------------
/plots/sethistName hist.root
  #
  #/gun/random on

  #
  #--------------------------------------------------------------------
  #  CERN 2009 2011
  #--------------------------------------------------------------------
  #
  #/gun/particle mu-
  #/gun/energy 120 GeV
  #/plots/sethistName hist_41_20_15v3_mu120G.root
  #
  #/gun/particle pi-
  #/gun/energy 100 GeV
  #/plots/sethistName hist_41_20_15v3_pi1100G_50um.root
  #
  #/gun/particle e-
  #/gun/energy 10 GeV


  #/plots/sethistName hist_41_20_15v4_e100G_50um.root
  #
  #--------------------------------------------------------------------
  #  DESY 09
  #--------------------------------------------------------------------
  #/gun/particle pi-
  #/gun/particle e-
  #/gun/energy 5000.0 MeV
  #/plots/sethistName hist_41_20_16v4n2_e5G.root
  #
  #--------------------------------------------------------------------
  #  Gamma sources Cd109=26 keV, Am241=59.5 keV
  #--------------------------------------------------------------------
  #/gun/particle gamma
  #/gun/energy 59.5 keV
  #--------------------------------------------------------------------
  #  IONs
  #--------------------------------------------------------------------
  #/gun/particle ion
  #/gun/ion 6 12 6
  #/gun/energy 5000.0 MeV
  #/gun/ion Z A Q
  #--------------------------------------------------------------------
/tracking/verbose 1
  #
  #/run/dumpCouples
  #/event/printModulo 1000
  #/run/beamOn 1
  #
  # --- print defined elements
  #/material/nist/printElement
  # --- print defined materials
  #/material/nist/listMaterials
  #===================================================================
  #                  J L E I C
  #===================================================================
/plots/sethistName      hist_jleic.root

# BEAGLE generator
/generator/select beagle
/generator/beagle/open beagle_test_data.txt
/generator/beagle/verbose 2

/run/beamOn 2
exit
