#------------------------------------------------------------------------
# Example macro. Process one of
#------------------------------------------------------------------------

# Include default setup
# Use jleic.mac for headless mode or jleicvis.mac for GUI visualization
/control/execute jleic.mac

# BEAGLE generator
/generator/select beagle
/generator/beagle/open /home/romanov/Downloads/beagle_eD.txt
/generator/beagle/verbose 2

/run/beamOn 10000
exit
