#------------------------------------------------------------------------
# Example macro. Process one of
#------------------------------------------------------------------------

# Include default setup
# Use jleic.mac for headless mode or jleicvis.mac for GUI visualization
/control/execute jleic.mac

# BEAGLE generator
/generator/select hepmcAscii
/generator/hepmcAscii/open /home/romanov/Downloads/herwig6_20k.hepmc
/generator/hepmcAscii/verbose 0
/run/initialize
/run/beamOn 1000
exit
