#------------------------------------------------------------------------
# Example macro. Process one of
#------------------------------------------------------------------------

# Include default setup
# Use jleic.mac for headless mode or jleicvis.mac for GUI visualization
/control/execute jleicvis.mac

# Select pythiaAScii generator
# Options are: particleGun hepmcAscii pythiaAscii beagle
/generator/select pythiaAscii


# Open file and run some MC file
#------ cone at 50mrad ----
#---protons ---
#/generator/pythiaAscii/open /data/yuliapc/home/yulia/work/g4e/resources/pythia/pythia_cone_p_200GeV_50mrad.txt
#------ cone at 25mrad ----
#---protons ---
/generator/pythiaAscii/open /data/yuliapc/home/yulia/work/g4e/resources/pythia/pythia_cone_p_275GeV_25mrad.txt
#---neutrons ---
#/generator/pythiaAscii/open /data/yuliapc/home/yulia/work/g4e/resources/pythia/pythia_cone_n_275GeV_25mrad.txt
#/generator/pythiaAscii/open /data/yuliapc/home/yulia/work/g4e/resources/pythia/pythia_1GeV_90.txt


#------- SETUP JLEIC beam lattice
/detsetup/beamlineName erhic
#-------- SETUP BEAM ENERGY-------

#/detsetup/eBeam 10
#/detsetup/pBeam 275
/run/initialize
#/run/beamOn 1
exit