# Default parameters for JLEIC detectors

#------------------------------------------------------------------------
# Macro file for the initialization phase
#------------------------------------------------------------------------
#
/control/verbose 0
/run/verbose 0
/geometry/navigator/verbose 0

#-------- SETUP BEAM ENERGY-------

/detsetup/eBeam 10
/detsetup/pBeam 275
#/detsetup/pBeam 200

#--------Detector construction ------------------


#-------------------------------------------------------
# Set XTR model (default: transpM). Name list consits:
# gammaR, gammaM, regR, regM, strawR, transpR, transpM
# R - XTR dE/dx models, M - XTR flux after radiator models
#-------------------------------------------------------
/emphyslist/setXTRModel  transpM
#/emphyslist/eMinEnergy 100.
#/emphyslist/gMinEnergy 100.
#
#/run/particle/applyCuts
# ----------set cuts in XTR radiator -----
/emphyslist/setRadiatorCuts 0.14
/emphyslist/setGammaCut    0.020
/emphyslist/setElectronCut 0.020
/emphyslist/setPositronCut 0.020
/emphyslist/setDetectorCuts 0.020
/run/initialize
#

#--------------------------------------------------------------------
/tracking/verbose 0
#
#/run/dumpCouples
#/event/printModulo 1000
# --- print defined elements
#/material/nist/printElement
# --- print defined materials
#/material/nist/listMaterials
# /plots/sethistName      hist_jleic.root



#===================================================================
#                 Input files  ( event generators)
#===================================================================

#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#^^^^^       single particle gun
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#/generator/fSelectCmd particleGun

#------------     run protons   ------------------------------------
#/gun/particle proton
#...............crossing angle 50mrad...............................
#/gun/momentum   -9.995833854   0.    199.7500520
#...............crossing angle 53 mrad .............................
#/gun/momentum   -10.5950381303   0.    199.719165748
#................ origin Vertex ....................................
####--- after iBDS1
#/gun/position -0.327111674     0   6.491761992  m
####--- before iQDS2
#/gun/position -0.687342971     0   13.28221363  m
####---- corrector
#/gun/position -0.936326367     0   17.97561402  m
#/gun/position -0.962813962     0   18.47491194 m
####--- This location is before entering  D2---
#/gun/position -1137.632091     0   21770.27817  mm
####--- This location is after exiting D2---
#/gun/position -1349.58247     0.   29766.53336   mm
####-- This location is before entering D3 ---
#/gun/position  -1349.58247     0   41314.67469      mm

#------------     run neutrons -------------------------------------
#/gun/particle neutron

#------    run gammas  Gamma sources Cd109=26 keV, Am241=59.5 keV-------
#/gun/particle gamma
#/gun/energy 59.5 keV
#------     run electrons -------------------------------------------
#/gun/particle e-
#/gun/particle pi-
#--------------------------------------------------------------------
#  IONs
#--------------------------------------------------------------------
#/gun/particle ion
#/gun/ion 6 12 6
#/gun/energy 5000.0 MeV
#/gun/ion Z A Q


#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#^^^^^^       BEAGLE generator
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#/generator/select beagle
#/generator/beagle/verbose 2
#----------------- file examples ----
#/generator/beagle/open BEAGLE.txt
#/generator/beagle/open  GCF_boosted.txt
#/generator/beagle/open  eD_5x50_Q2_1_10_y_0.01_0.95_tau_7_noquench_kt=ptfrag=0.32_Shd1_ShdFac=1.32_Jpsidifflept_test40k_fixpf_crang.txt
#/generator/beagle/open  eD_5x100_Q2_1_max_y_0.01_0.95_10k_Shd3_tau7_kt=ptfrag=0.32_shdfac=1.32.Jpsidiffnodecay.Kongpf.txt
#/generator/beagle/open eD_5x200_Q2_1_80_y_0.01_0.95_10k_Shd3_tau7_kt=ptfrag=0.32_shdfac=1.32.JpsidiffdecayLeptons.Kongpf.txt
#/generator/beagle/open  eD_5x50_Q2_1_10_y_0.01_0.95_tau_7_noquench_kt=ptfrag=0.32_Shd1_ShdFac=1.32_Jpsidifflept_test40k_wrongpf_crang.txt

#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#^^^^^^      Pythia6  GEMC/BNL version
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#/generator/select pythiaAscii
#/generator/pythiaAscii/verbose 1
#----------------- file examples ----
#/generator/pythiaAscii/open  pythia1pis.txt
#/generator/pythiaAscii/open  /home/yulia/yulia/TestVTXhmc/build.newnewOK/pythiaBeautyDIS100.txt
#/generator/pythiaAscii/open  pythia_e-p_10x50_Q2_100k_msel2_DIS.txt
#/generator/pythiaAscii/open  /home/yulia/GEMC/detectors/eic/script/pythia-PHP.txt
#/generator/pythiaAscii/open /data/yulia/yulia-PCbackup/EIC-soft/pythia_jlab_v2/pythia/work/pythia_e-p_10x100_Q0_100k_msel2_PHP.txt
#/generator/pythiaAscii/open  /data/yulia/yulia-PCbackup/EIC-soft/pythia_jlab/pythiaeRHIC/1.0.0/build_old2/pythia_PHP_Charm.txt
#/generator/pythiaAscii/open  /data/yulia/yulia-PCbackup/EIC-soft/pythia_jlab/pythiaeRHIC/1.0.0/build_old2/pythia_PhP.txt
#/generator/pythiaAscii/open  /home/yulia/GEMC/detectors/eic/script/jpsi_ee.txt
#/generator/pythiaAscii/open  synch2.dat
#/generator/pythiaAscii/open  synch14.dat
#/generator/pythiaAscii/open  synch100.dat


#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#^^^^^^      Pythia6  cone  - file examples
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#------ cone at 50mrad ----
#---protons ---
#/generator/pythiaAscii/open /data/yuliapc/home/yulia/work/g4e/resources/pythia/pythia_cone_p_200GeV_50mrad.txt
#---neutrons ---
#/generator/pythiaAscii/open /data/yuliapc/home/yulia/work/g4e/resources/pythia/pythia_cone_n_200GeV_50mrad.txt
#---electrons ---
#/generator/pythiaAscii/open /data/yuliapc/home/yulia/work/g4e/resources/pythia/pythia_cone_e_10GeV_0.txt
#/generator/pythiaAscii/open /data/yuliapc/home/yulia/work/g4e/resources/pythia/pythia_cone_e_10GeV_0_upstream.txt



#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#^^^^^        HepMc v2.x ascii files
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#/generator/fSelectCmd hepmcAscii
#/generator/hepmcAscii/verbose 1

#---- Herwig Charm------
#/generator/hepmcAscii/open  /data/yulia/Herwig6/herwig6_P19104_Q10_N5e+06_e-p_5x100.hepmc
#---- Pythia6 Charged current ------
#/generator/hepmcAscii/open pythia8_CCdis.hepmc
#/generator/hepmcAscii/open  /data/yulia/Herwig6/herwig6_P19010_Q100_N1e+06_e+p_5x200.hepmc


exit
