
/run/initialize

#/vis/open VRML2FILE
#/vis/drawVolume
#/vis/viewer/flush

#/persistency/gdml/write jleic.gdml

# Use this open statement to create an OpenGL view:
### This works  ->   
#/control/manual vis
/vis/list
/vis/open OGL 1000x800-0+0
#/vis/open OGLI 600x600-0+0
#/vis/open OGLIX 600x600-0+0
#/vis/open OGLIQt 1000x800-0+0
# 
#
#/vis/open OGLS 600x600-0+0
#/vis/open OGLSX 600x600-0+0
#/vis/open OGLIQt 1000x800-0+0
#/vis/open OGLIQt_FALLBACK 600x600-0+0
#/vis/open OGLSQt_FALLBACK 600x600-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi  90. 0.
#/vis/viewer/set/viewpointThetaPhi -90. 0.
#/vis/viewer/set/viewpointThetaPhi 0. 0.
#/vis/viewer/set/viewpointThetaPhi 0. 0.
#/vis/viewer/set/viewpointThetaPhi 90.0000 89.99999999
/vis/viewer/set/viewpointThetaPhi -90.0000 -89.99999999
#/vis/viewer/set/viewpointThetaPhi -135. -135.
#
# Specify zoom value:
#/vis/viewer/zoom 50.
/vis/viewer/zoom 2.
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 1 m
#/vis/geometry/set/visibility World_Logic 0 true
#/vis/scene/add/magneticField 100
#/vis/scene/add/magneticField 300 lightArrow
###/vis/scene/add/magneticField 100
#
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
# /vis/filtering/trajectories/create/particleFilter
# /vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#fsv /vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to fSelectCmd colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/list
/vis/modeling/trajectories/drawByParticleID-0/set e- cyan
/vis/modeling/trajectories/drawByParticleID-0/set e+ gray
/vis/modeling/trajectories/drawByParticleID-0/set kaon- magenta
/vis/modeling/trajectories/drawByParticleID-0/set kaon+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set pion+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set pion- magenta
/vis/modeling/trajectories/drawByParticleID-0/set muon- red
/vis/modeling/trajectories/drawByParticleID-0/set muon+ red
/vis/modeling/trajectories/drawByParticleID-0/set pion0 blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set proton blue
/vis/modeling/trajectories/drawByParticleID-0/set neutron gray
/vis/modeling/trajectories/drawByParticleID-0/set lambda green
#/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
#
# To superimpose all of the events from a given run:
# /vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
#
#-----------------------------------------------------------------------
#/control/execute depfet09.mac
#-----------------------------------------------------------------------
#/control/execute vtx.mac
/vis/viewer/set/background 1 1 1

/vis/scene/endOfEventAction accumulate 100

#/vis/viewer/set/cutawayMode intersection
/vis/viewer/clearCutawayPlanes

/vis/viewer/addCutawayPlane 0  30  0  cm  0. -500 0
#/vis/viewer/addCutawayPlane 0  1  0  cm  0. -0.1 0
#/vis/viewer/addCutawayPlane 0  1  0  cm  0. -500. 1.
#/vis/viewer/addCutawayPlane 0  1  0  cm  0. 100. 1.
# XY 
#/vis/viewer/addCutawayPlane  1  0  0  cm   0  0  -0.001
#  ZY
#/vis/viewer/addCutawayPlane 0  1  0  cm  -0.001 0  0
#/vis/viewer/clearCutawayPlanes
#/run/initialize
#/run/beamOn 1
#--------------CMS vis
#/vis/viewer/set/viewpointThetaPhi -30. -30.
#/vis/viewer/zoomTo 100

#========= CMS view =========================
#/vis/viewer/addCutawayPlane 0 0 7 m 0 0 1
#/vis/viewer/addCutawayPlane 0 0 7 m 1 0 0
#/vis/viewer/addCutawayPlane 0 0 7 m 0 -1 0
#/vis/viewer/set/style surface
#/vis/viewer/colourByDensity 1 g/cm3 .5 3 10
#---------------------------------------------------
/vis/viewer/zoom 0.5
/vis/viewer/set/viewpointThetaPhi -90 -45 deg
/vis/viewer/zoom 100

exit
