#------------------------------------------------------------------------
# Example macro. Process one of
#------------------------------------------------------------------------

# Include default setup
# Use jleic.mac for headless mode or jleicvis.mac for GUI visualization
#/control/execute jleicvis.mac
/control/execute jleicvis.mac

# Select pythiaAScii generator
# Options are: particleGun hepmcAscii pythiaAscii beagle
/generator/select pythiaAscii


# Open file and run some MC file
#------ cone at 50mrad ----
#---protons ---
/generator/pythiaAscii/open  /data/yulia/yulia-PCbackup/EIC-soft/pythia_jlab_v2/pythia/work/pythia_e-p_10x100_Q2_100k_msel2_DIS.txt

/run/initialize
/run/beamOn 1

exit