//
// ********************************************************************
// * License and Disclaimer                                           *
// *                                                                  *
// * The  Geant4 software  is  copyright of the Copyright Holders  of *
// * the Geant4 Collaboration.  It is provided  under  the terms  and *
// * conditions of the Geant4 Software License,  included in the file *
// * LICENSE and available at  http://cern.ch/geant4/license .  These *
// * include a list of copyright holders.                             *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.  Please see the license in the file  LICENSE  and URL above *
// * for the full disclaimer and the limitation of liability.         *
// *                                                                  *
// * This  code  implementation is the result of  the  scientific and *
// * technical work of the GEANT4 collaboration.                      *
// * By using,  copying,  modifying or  distributing the software (or *
// * any work based  on the software)  you  agree  to acknowledge its *
// * use  in  resulting  scientific  publications,  and indicate your *
// * acceptance of all terms of the Geant4 Software license.          *
// ********************************************************************
//
/// \file eventgenerator/HepMC/HepMCEx01/include/PythiaInterface.hh
/// \brief Definition of the PythiaInterface class
//
// $Id: PythiaInterface.hh 77801 2013-11-28 13:33:20Z gcosmo $
//

#ifndef PYTHIA_INTERFACE_H
#define PYTHIA_INTERFACE_H

#include "G4LorentzVector.hh"
#include "G4VPrimaryGenerator.hh"
#include "G4UnitsTable.hh"
#include "G4SystemOfUnits.hh"

class PythiaAsciiReader;
/// A base class for primary generation via HepMC object.
/// This class is derived from G4VPrimaryGenerator.

class PythiaInterface : public G4VPrimaryGenerator {
protected:
 
  // We  have to take care for the position of primaries because
  // primary vertices outside the world voulme give rise to G4Execption.
  // If the default implementation is not adequate, an alternative
  // can be implemented in your own class.
  virtual G4bool CheckVertexInsideWorld(const G4ThreeVector& pos) const;

  // service method for conversion from Pythia/LUND arrais to G4Event
  void PyMC2G4(const PythiaAsciiReader* pyevt, G4Event* g4event);

  // Implement this method in his/her own concrete class.
  // An empty event will be created in default.
  virtual PythiaAsciiReader* GeneratePythiaEvent();

public:
  PythiaInterface();
  virtual ~PythiaInterface();

  // The default behavior is that a single Py/LUND event generated by
  // GeneratePythiaEvent() will be converted to G4Event through PyMC2G4().
  virtual void GeneratePrimaryVertex(G4Event* anEvent);
};

#endif
